/**
 * React entry point — renders the app into #root.
 *
 * This file is part of the boilerplate — NOT generated by /setup.
 * /setup only replaces __PROJECT_NAME__ with the actual project name.
 */

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Providers } from "./providers";
import { Router } from "./router";
import "@/styles/globals.css";

const rootElement = document.getElementById("root");
if (!rootElement) {
  throw new Error("Root element not found. Check index.html has <div id='root'>.");
}

createRoot(rootElement).render(
  <StrictMode>
    <Providers>
      <Router />
    </Providers>
  </StrictMode>,
);
