/**
 * AppModule — Root module of the NestJS application.
 *
 * This file is part of the boilerplate — NOT generated by /setup.
 * Register all feature modules here.
 *
 * PATTERN: Import feature modules, NOT individual controllers/services.
 * Each feature module handles its own wiring.
 *
 * When running `npm run scaffold:clean`, DummiesModule import will be removed.
 */

import { Module } from "@nestjs/common";
import { DummiesModule } from "./modules/dummies/dummies.module";

@Module({
  imports: [DummiesModule],
})
export class AppModule {}
