/**
 * AppModule — Root module of the NestJS application.
 *
 * This file is part of the boilerplate — NOT generated by /setup.
 * Register all feature modules here.
 *
 * PATTERN: Import feature modules, NOT individual controllers/services.
 * Each feature module handles its own wiring.
 */

import { Module } from "@nestjs/common";
import { HealthModule } from "./modules/health/health.module";

@Module({
  imports: [HealthModule],
})
export class AppModule {}
