/**
 * NestJS Application Entry Point.
 *
 * Bootstraps the app with global pipes, filters, interceptors, and Swagger.
 * This file is part of the boilerplate — NOT generated by /setup.
 */

import { ValidationPipe } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { AppModule } from "./app.module";
import { HttpExceptionFilter } from "@/common/filters/http-exception.filter";
import { LoggingInterceptor } from "@/common/interceptors/logging.interceptor";
import { TransformInterceptor } from "@/common/interceptors/transform.interceptor";

async function bootstrap(): Promise<void> {
  const app = await NestFactory.create(AppModule);

  // Global prefix
  app.setGlobalPrefix("api/v1");

  // CORS — allow frontend dev server
  app.enableCors({
    origin: [
      "http://localhost:5173", // Vite dev server
      "http://localhost:3000", // Same origin
    ],
    credentials: true,
  });

  // Global pipes
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
    }),
  );

  // Global filters & interceptors
  app.useGlobalFilters(new HttpExceptionFilter());
  app.useGlobalInterceptors(
    new LoggingInterceptor(),
    new TransformInterceptor(),
  );

  // Swagger
  const config = new DocumentBuilder()
    .setTitle("API Documentation")
    .setDescription("Auto-generated API documentation")
    .setVersion("0.1.0")
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup("api/docs", app, document);

  // Start server
  const port = process.env["PORT"] ?? 3000;
  await app.listen(port);

  // Log startup info via NestJS Logger
  const { Logger } = await import("@nestjs/common");
  const logger = new Logger("Bootstrap");
  logger.log(`Server running on http://localhost:${port}`);
  logger.log(`Swagger docs at http://localhost:${port}/api/docs`);
}

void bootstrap();
